From ros:noetic-ros-core

RUN apt update && apt install -y python3-catkin-tools git python3-vcstool \
build-essential \
cmake-curses-gui \
libboost-dev \
libboost-system-dev \
libboost-program-options-dev \
libboost-iostreams-dev \
libeigen3-dev \
uuid-dev \
libxfixes-dev \
libyaml-dev \
libfmt-dev \
gettext \
zlib1g-dev \
libjpeg-dev \
libpng-dev \
libfreetype-dev \
qtbase5-dev \
libqt5x11extras5-dev \
libqt5svg5-dev \
qttranslations5-l10n \
python3-dev \
python3-numpy \
libassimp-dev \
libode-dev \
libfcl-dev \
libpulse-dev \
libsndfile1-dev \
libgstreamer1.0-dev \
libgstreamer-plugins-base1.0-dev \
ros-noetic-image-transport ros-noetic-angles ros-noetic-ros-controllers \
ros-noetic-joint-limits-interface ros-noetic-transmission-interface \
ros-noetic-urdf-tutorial
RUN apt install -y liburdfdom-tools